### ISSUE TITLE
Fix error when trying to `hop deploy -y`

### ISSUE THREAD

**Issue by antoinekm** [hopinc/hop_cli#15]
**How to reproduce**
1. Go to the project directory you want to deploy
2. Delete `hop.yml` if you have one
3. Run `hop deploy -y`
4. You might see this error:
```sh
> hop deploy -y    
info: Attempting to deploy ./yourprojectdir
info: No hopfile found, creating one
info: Deploying to project project_name  /project  project_id  date  regular
warn: Using default config, skipping arguments
error: body.restart_policy should be equal to one of the allowed values
```

**Expected behavior**
The restart policy on_failure should work fine by default and allowed

**Comment by pxseu** [comment]
Fixed in https://github.com/hopinc/cli/tree/v0.2.37

Thanks for reporting!
