### ISSUE TITLE
`hop auth login` with `--token` option fails in newer versions

### ISSUE THREAD

**Issue by phips-git** [hopinc/hop_cli#16]
Hey there,

I'm current embedding the hop.io CLI within a Github Actions workflow. Installation works fine, but when I run the `hop auth login` command with the project token in the `--token` option, it gives me the following error for all newer versions. 

When I try the exact same procedure with the version stated in the docs (v0.1.46) (https://docs.hop.io/cli/ci#example) it works fine.

Have you encountered this error already?

![Screenshot 2023-08-04 at 08 02 51](https://github.com/hopinc/cli/assets/44228158/ebd80b77-6cc7-4d08-ad5e-63b206449b02)

**Comment by pxseu** [comment]
Hi, 

Are you possibly using a version pre [`v0.2.47`](https://github.com/hopinc/cli/releases/tag/v0.2.47)? This version should've fixed that issue in https://github.com/hopinc/cli/commit/4e03256d4bb60e8089be09d0a469cd7d400729cb. 
Let me know if that helps.

Cheers

**Comment by phips-git** [comment]
Nope, it was actually with the latest one `v0.2.52`. The bug was introduced somewhere between `v0.1.47` and today, because with `v0.1.47` it is not showing this error.

**Comment by pxseu** [comment]
Okay, found the culprit. Should be fixed in [`v0.2.53`](https://github.com/hopinc/cli/releases/tag/v0.2.53).

**Comment by phips-git** [comment]
Thank you for the quick fix. The message isn't shown anymore. 
But now I have the next issue: Running your "deploy to hop" Github Actions with the latest version is stuck in this phase forever and won't finish after hours until I manually cancel the workflow. Have you seen this before also?

<img width="390" alt="Screenshot 2023-08-07 at 10 35 17" src="https://github.com/hopinc/cli/assets/44228158/e99309b1-d8ab-4de0-af71-3931f28a3a61">

**Comment by pxseu** [comment]
Okay, there was a small issue on our backend. Everything should be fixed now, however you will need to re-create your project token in the dashboard https://console.hop.io/project/settings/tokens.
Sorry for the inconvenience.

**Comment by phips-git** [comment]
@pxseu works like a charm now, thank you very much for the quick support!
