### ISSUE TITLE
hop deploy -> Gateway Timeout

### ISSUE THREAD

**Issue by reddytocode** [hopinc/hop_cli#18]
I've been using Hop CLI for my deployments but now I'm getting 504 on my terminal while the process gets successfully executed in the Hope servers

1. `hop deploy`
2. Hop says it is pending
<img width="819" alt="Screenshot 2023-11-08 at 18 52 15" src="https://github.com/hopinc/cli/assets/20909101/a9d321c6-3f0f-4e61-b8c9-92b2c8f4f908">
3. CLI throws `error: HTTP 504: Gateway Timeout`
<img width="880" alt="Screenshot 2023-11-08 at 18 50 02" src="https://github.com/hopinc/cli/assets/20909101/951ff524-aaf7-464b-ae8a-46ffc92322be">

Happy to provide more details if needed 😄

**Comment by pxseu** [comment]
Issue fixed
