### ISSUE TITLE
Installation script doesn't work

### ISSUE THREAD

**Issue by nexxeln** [hopinc/hop_cli#5]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/95541290/185998303-9d3e5e74-6b71-450d-bf6e-a25313a61999.png">

OS: WSL2 Ubuntu
Shell: zsh

Error: 
```
sh: 4: [: x1000: unexpected operator
sh: 21: [[: not found
sh: 21: [[: not found
sh: 21: [[: not found
sh: 25: [[: not found
sh: 25: [[: not found
sh: 25: [[: not found
sh: 29: [[: not found
sh: 29: [[: not found
sh: 29: [[: not found
sh: 37: [[: not found
sh: 41: HOP_VERSION: parameter not set
```

**Comment by pxseu** [comment]
fixed in https://github.com/hopinc/hop_cli/commit/a963fccab050cbbc65202d20eca9f57252b51e1b, will be glad if you can confirm this for me

**Comment by nexxeln** [comment]
Works! Still get those errors though.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/95541290/186101234-4721d6df-c17b-481b-946c-d5df088a3ee6.png">

**Comment by pxseu** [comment]
kk could you check now? added quotes so it might be fine now (https://github.com/hopinc/hop_cli/commit/bef66645bf13a4d586ed487a4fd7fd89849472be)

**Comment by nexxeln** [comment]
Works!
